import { StyleSheet } from "react-native";
import {
  widthPercentageToDP as wp,
  heightPercentageToDP as hp,
} from "react-native-responsive-screen";
export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#347AF0",
    height: hp("100%"),
  },
  _data_main: {
    flex: 1,
    backgroundColor: "#fff",
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    paddingHorizontal: 20,
    paddingTop: 20,
  },
  _header_main: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 20,
    paddingTop: hp("3%"),
    backgroundColor: "#347AF0",
  },
  _header_heading: {
    color: "#fff",
    fontFamily: "TitilliumWeb-SemiBold",
    fontSize: hp("4%"),
  },
  _drawer_icon: {
    width: 40,
    height: 40,
    borderRadius: 40 / 2,
    alignItems: "center",
    justifyContent: "center",
  },
  _price: {
    color: "#fff",
    fontFamily: "TitilliumWeb-Bold",
    fontSize: hp("4%"),
    textAlign: "center",
    marginTop: hp("2%"),
  },
  _wallet_title: {
    color: "#fff",
    fontFamily: "TitilliumWeb-Regular",
    fontSize: hp("2%"),
    textAlign: "center",
  },
  _card_heading: {
    color: "#0D1F3C",
    fontFamily: "TitilliumWeb-SemiBold",
    fontSize: hp("3%"),
  },
  _deposit_btn: {
    backgroundColor: "#fff",
    marginTop: hp("2%"),
    height: hp("10%"),
    borderRadius: 50,
    paddingHorizontal: 20,
    paddingVertical: 10,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: "#9EA5B1",
    borderStyle: "dashed",
  },
  _deposit_btn_text: {
    color: "#B5BBC9",
    fontFamily: "TitilliumWeb-SemiBold",
    fontSize: hp("3%"),
  },
  _all_accets: {
    color: "#347AF0",
    fontFamily: "TitilliumWeb-SemiBold",
    fontSize: hp("2.5%"),
    marginTop: hp("3%"),
    textAlign: "center",
    marginBottom:hp("2%")
  },
  _toash_message_main: {
    backgroundColor: "#0D1F3C",
    position: "absolute",
    width: "86%",
    alignSelf: "center",
    borderRadius: 50,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 20,
    height:hp("7%"),
    marginTop:hp("3%")
  },
  _toash_category_main: {
    flexDirection: "row",
    alignItems: "center",
  },
  _toash_close_btn: {
    // backgroundColor: "white",
    width: 20,
    height: 20,
    borderRadius: 20 / 2,
    alignItems: "center",
    justifyContent: "center",
  },
  _toash_category_icon: {
    backgroundColor: "#DF5060",
    width: 20,
    height: 20,
    borderRadius: 20 / 2,
    alignItems: "center",
    justifyContent: "center",
  },
  _toash_message: {
    color: "#fff",
    fontFamily: "TitilliumWeb-SemiBold",
    fontSize: 15,
    marginLeft: 10,
  },
});
